spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: SECTOR-SERVICE
          uri: lb://SECTOR-SERVICE
          predicates:
            - Path= /sector/**
          filters:
            - name: CircuitBreaker
              args:
                name: SECTOR-SERVICE
                fallbackuri: forward:/sectorServiceFallback
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/arrangements/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: WORK-SERVICE
          uri: lb://WORK-SERVICE
          predicates:
            - Path=/work/**
          filters:
            - name: CircuitBreaker
              args:
                name: WORK-SERVICE
                fallbackuri: forward:/workServiceFallback
        - id: FEEDBACK-SERVICE
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/feedback/**
          filters:
            - name: CircuitBreaker
              args:
                name: FEEDBACK-SERVICE
                fallbackuri: forward:/feedbackServiceFallBack
        - id: SECTOR-SERVICE
          uri: lb://SECTOR-SERVICE
          predicates:
            - Path=/company/**
          filters:
            - name: CircuitBreaker
              args:
                name: SECTOR-SERVICE
                fallbackuri: forward:/sectorServiceFallBack
server:
  port: 9191
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka