spring:
  cloud:
    gateway:
      routes:
        - id: SECTOR-SERVICE
          uri: JanaM://SECTOR-SERVICE
          predicates:
            - Path= /sectors/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: USER-SERVICE
          uri: JanaM://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: SECTOR-SERVICE
                fallbackuri: forward:/sectorServiceFallBack
        - id: WORK-SERVICE
          uri: JanaM://WORK-SERVICE
          predicates:
            - Path=/work/**
          filters:
            - name: CircuitBreaker
              args:
                name: WORK-SERVICE
                fallbackuri: forward:/workServiceFallback
        - id: FEEDBACK-SERVICE
          uri: JanaM://FEEDBACK-SERVICE
          predicates:
            - Path=/feedback/**
          filters:
            - name: CircuitBreaker
              args:
                name: FEEDBACK-SERVICE
                fallbackuri: forward:/feedbackServiceFallBack
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutinmiliseconds: 4000